version: '3'

services:
    fluentd:
        build: ./fluentd

        volumes:
            - ./fluentd/fluentd.conf:/fluentd/etc/fluentd.conf:ro

        ports:
            - 24224:24224

        environment:
            FLUENTD_CONF: fluentd.conf

    elasticsearch:
        image: elasticsearch:7.9.1

        depends_on:
            - fluentd

        environment:
            discovery.type: single-node
    kibana:
        build: ./kibana

        ports:
            - 5601:5601

        depends_on:
            - elasticsearch
